package unhappycodings.thoriumreactors.common;

import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import unhappycodings.thoriumreactors.common.registration.ModBlocks;

import java.util.List;

public class TurbineMultiblocks {

    private static final List<Block> TURBINE_5X5X10_3VENTS = List.of(
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_ROTATION_MOUNT.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.ELECTROMAGNETIC_COIL.get(), ModBlocks.ELECTROMAGNETIC_COIL.get(), ModBlocks.ELECTROMAGNETIC_COIL.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.ELECTROMAGNETIC_COIL.get(), ModBlocks.TURBINE_ROTOR.get(), ModBlocks.ELECTROMAGNETIC_COIL.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.ELECTROMAGNETIC_COIL.get(), ModBlocks.ELECTROMAGNETIC_COIL.get(), ModBlocks.ELECTROMAGNETIC_COIL.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_VENT.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.TURBINE_ROTOR.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, ModBlocks.TURBINE_ROTOR.get(), Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, ModBlocks.TURBINE_ROTOR.get(), Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, ModBlocks.TURBINE_ROTOR.get(), Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, ModBlocks.TURBINE_ROTOR.get(), Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, ModBlocks.TURBINE_ROTOR.get(), Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CONTROLLER_BLOCK.get(), Blocks.AIR, ModBlocks.TURBINE_ROTOR.get(), Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_GLASS.get(), Blocks.AIR, Blocks.AIR, Blocks.AIR, ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_VALVE.get(), ModBlocks.TURBINE_GLASS.get(), ModBlocks.TURBINE_CASING.get(),
            ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_ROTATION_MOUNT.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get(), ModBlocks.TURBINE_CASING.get());

    public static List<Block> getTurbine5x5x10_3vents() {
        return TURBINE_5X5X10_3VENTS;
    }

    public static boolean isTurbine5x5x10_3Vents(List<Block> blocks) {

        for (int i = 0; i < TURBINE_5X5X10_3VENTS.size(); i++) {
            if (TURBINE_5X5X10_3VENTS.get(i) != blocks.get(i))
                return false;
        }

        return true;
    }

}
