modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "thoriumreactors"
version = "${file.jarVersion}"
displayName = "ThoriumReactors"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/thorium-reactors"
logoFile = "thoriumreactors-logo.png"
authors = "UnhappyWithoutU"
description = ""

[[dependencies.thoriumreactors]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thoriumreactors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thoriumreactors]]
modId = "ctm"
mandatory = false
versionRange = "[1.1.7+11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.thoriumreactors]]
modId = "computercraft"
mandatory = false
versionRange = "[1.101.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thoriumreactors]]
modId = "theoneprobe"
mandatory = false
versionRange = "[1.19-6.2.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thoriumreactors]]
modId = "jade"
mandatory = false
versionRange = "[8.8.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thoriumreactors]]
modId = "jei"
mandatory = false
versionRange = "[11.4.0.288,)"
ordering = "NONE"
side = "BOTH"
