modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "thoriumreactors"
version = "${file.jarVersion}"
displayName = "ThoriumReactors"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/thorium-reactors"
logoFile = "thoriumreactors-logo.png"
authors = "UnhappyWithoutU"
description = ""

[[dependencies.thoriumreactors]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thoriumreactors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thoriumreactors]]
modId = "computercraft"
mandatory = false
versionRange = "[1.108.3,)"
ordering = "NONE"
side = "BOTH"
